# Generated by Django 3.2.14 on 2022-08-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custormer',
            new_name='Customer',
        ),
    ]
