# Generated by Django 3.2.14 on 2022-08-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_picture_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='picture_file',
            new_name='profile_pic',
        ),
    ]
